# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KiSbV8LjNmoHfmlU3q0GLrvw5wQxeNtv
"""

def print_board(board):
    print("-------------")
    for i in range(3):
        print("|", end="")
        for j in range(3):
            print(" " + board[i][j] + " |", end="")
        print("\n-------------")

def check_winner(board):
    # Sprawdzenie wygranej w wierszach
    for i in range(3):
        if board[i][0] == board[i][1] == board[i][2] != " ":
            return board[i][0]

    # Sprawdzenie wygranej w kolumnach
    for j in range(3):
        if board[0][j] == board[1][j] == board[2][j] != " ":
            return board[0][j]

    # Sprawdzenie wygranej na przekątnych
    if board[0][0] == board[1][1] == board[2][2] != " ":
        return board[0][0]
    if board[0][2] == board[1][1] == board[2][0] != " ":
        return board[0][2]

    # Remis
    is_full = True
    for i in range(3):
        for j in range(3):
            if board[i][j] == " ":
                is_full = False
    if is_full:
        return "Tie"

    # Brak zwycięzcy
    return None

def play_game():
    board = [[" " for _ in range(3)] for _ in range(3)]
    current_player = "X"
    winner = None

    while not winner:
        print_board(board)
        print("It's Player", current_player, "turn.")
        row = int(input("Enter the row (0-2): "))
        col = int(input("Enter the column (0-2): "))

        if board[row][col] == " ":
            board[row][col] = current_player
            winner = check_winner(board)
            if current_player == "X":
                current_player = "O"
            else:
                current_player = "X"
        else:
            print("Invalid move. Try again.")

    print_board(board)

    if winner == "Tie":
        print("It's a tie!")
    else:
        print("Player", winner, "wins!")

play_game()